<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE xml [
<!ELEMENT xml (OrgQuestion*)>
<!ATTLIST xml 
version CDATA #REQUIRED
>
<!ELEMENT OrgQuestion (OrgQSubject, OrgQBody, Thread)>
<!ATTLIST OrgQuestion 
ORGQ_ID CDATA #REQUIRED
>
<!ELEMENT OrgQSubject (#PCDATA)>
<!ELEMENT OrgQBody (#PCDATA)>
<!ELEMENT Thread (RelQuestion, RelComment*)>
<!ATTLIST Thread
 THREAD_SEQUENCE CDATA #REQUIRED
 SubtaskA_Skip_Because_Same_As_RelQuestion_ID CDATA #IMPLIED
>
<!ELEMENT RelQuestion (RelQSubject, RelQBody)>
<!ATTLIST RelQuestion
RELQ_ID CDATA #REQUIRED
RELQ_RANKING_ORDER CDATA #REQUIRED
RELQ_CATEGORY CDATA #REQUIRED
RELQ_DATE CDATA #REQUIRED
RELQ_USERID CDATA #REQUIRED
RELQ_USERNAME CDATA #REQUIRED
RELQ_RELEVANCE2ORGQ CDATA #REQUIRED
>
<!ELEMENT RelQSubject (#PCDATA)>
<!ELEMENT RelQBody (#PCDATA)>
<!ELEMENT RelComment (RelCText)>
<!ATTLIST RelComment
RELC_ID CDATA #REQUIRED
RELC_DATE CDATA #REQUIRED
RELC_USERID CDATA #REQUIRED
RELC_USERNAME CDATA #REQUIRED
RELC_RELEVANCE2ORGQ CDATA #REQUIRED
RELC_RELEVANCE2RELQ CDATA #REQUIRED
>
<!ELEMENT RelCText (#PCDATA)>
]>
<xml version="1.0">

<OrgQuestion ORGQ_ID="Q201">
	<OrgQSubject>which mobile is best under 2000QR</OrgQSubject>
	<OrgQBody>i want to buy new mobile.... and i want to know which mobile is best is under 2000QR....</OrgQBody>

	<Thread THREAD_SEQUENCE="Q201_R7" SubtaskA_Skip_Because_Same_As_RelQuestion_ID="Q46_R12">
		<RelQuestion RELQ_ID="Q201_R7" RELQ_RANKING_ORDER="7" RELQ_CATEGORY="Welcome to Qatar" RELQ_DATE="2009-07-30 11:45:31" RELQ_USERID="U1684" RELQ_USERNAME="DonIsGood" RELQ_RELEVANCE2ORGQ="Irrelevant">
			<RelQSubject>QR1;500/month Car Rental???</RelQSubject>
			<RelQBody>G'day all; A mate of mine was renting a car for QR1;500/month !!!; just wondering if any one knows or has a contact for such? Unfortunately my mate left last month and I lost his email address in between; hence I am unable to ask him direct. Cheers; Don</RelQBody>
		</RelQuestion>

		<RelComment RELC_ID="Q201_R7_C1" RELC_DATE="2009-07-30 12:32:58" RELC_USERID="U1685" RELC_USERNAME="dohaboytoy" RELC_RELEVANCE2ORGQ="PotentiallyUseful" RELC_RELEVANCE2RELQ="Good">
			<RelCText>The cheapest I know is 1600. I will give you the contact number if you are interested http://smalltalketc.blogspot.com</RelCText>
		</RelComment>

		<RelComment RELC_ID="Q201_R7_C2" RELC_DATE="2009-07-30 13:00:17" RELC_USERID="U1684" RELC_USERNAME="DonIsGood" RELC_RELEVANCE2ORGQ="Bad" RELC_RELEVANCE2RELQ="Bad">
			<RelCText>Yes please dohaboytoy! I have just PM you; look forward to your reply and thanks for your kind assistance. Cheers; Don</RelCText>
		</RelComment>

		<RelComment RELC_ID="Q201_R7_C3" RELC_DATE="2009-08-01 00:55:53" RELC_USERID="U1686" RELC_USERNAME="basharhabib" RELC_RELEVANCE2ORGQ="Bad" RELC_RELEVANCE2RELQ="Bad">
			<RelCText>I am interested too; kindly email me the numbers. Thx</RelCText>
		</RelComment>

		<RelComment RELC_ID="Q201_R7_C4" RELC_DATE="2009-08-01 10:30:04" RELC_USERID="U1687" RELC_USERNAME="sunflowergirl" RELC_RELEVANCE2ORGQ="Bad" RELC_RELEVANCE2RELQ="Bad">
			<RelCText>me too. thanks a lot</RelCText>
		</RelComment>

		<RelComment RELC_ID="Q201_R7_C5" RELC_DATE="2009-08-20 21:48:44" RELC_USERID="U1688" RELC_USERNAME="paulantypas" RELC_RELEVANCE2ORGQ="Bad" RELC_RELEVANCE2RELQ="Bad">
			<RelCText>Dohaboytoy; can you please provide me the details for that offer of 1600/month</RelCText>
		</RelComment>

		<RelComment RELC_ID="Q201_R7_C6" RELC_DATE="2009-08-20 22:16:49" RELC_USERID="U659" RELC_USERNAME="umm-salayum" RELC_RELEVANCE2ORGQ="Bad" RELC_RELEVANCE2RELQ="Good">
			<RelCText>we used to rent a car for 1490 QAR a month ; but you have to make a 6 months contract with them; it is called Oasis rental car ; i don't know if they still have the same deal</RelCText>
		</RelComment>

		<RelComment RELC_ID="Q201_R7_C7" RELC_DATE="2009-08-21 10:52:03" RELC_USERID="U1688" RELC_USERNAME="paulantypas" RELC_RELEVANCE2ORGQ="Bad" RELC_RELEVANCE2RELQ="Good">
			<RelCText>You are right; Oasis Rant a car is advertising in the Marhaba Qatar's info guide: 1.395/month. (min. 6 months) Does anybody know other companies offering similar deals? Regards</RelCText>
		</RelComment>

		<RelComment RELC_ID="Q201_R7_C8" RELC_DATE="2009-08-21 11:05:00" RELC_USERID="U1689" RELC_USERNAME="Bunga" RELC_RELEVANCE2ORGQ="Bad" RELC_RELEVANCE2RELQ="Good">
			<RelCText>Al Obaidly Trading; 5th Floor at Mercure Hotel. We rented there for qr1800; but there are packages at qr1500. Look for Thomas Chacko. Cheers. *Bunga*</RelCText>
		</RelComment>

		<RelComment RELC_ID="Q201_R7_C9" RELC_DATE="2009-08-21 11:13:54" RELC_USERID="U366" RELC_USERNAME="Dracula" RELC_RELEVANCE2ORGQ="Bad" RELC_RELEVANCE2RELQ="Bad">
			<RelCText>don't rent! better buy a car! .</RelCText>
		</RelComment>

		<RelComment RELC_ID="Q201_R7_C10" RELC_DATE="2010-01-02 16:39:37" RELC_USERID="U1690" RELC_USERNAME="MisterHarris" RELC_RELEVANCE2ORGQ="Bad" RELC_RELEVANCE2RELQ="PotentiallyUseful">
			<RelCText>Like Dracula said; buy; dont rent...but for that price; you can go to Obeidly (in Sofitel)...but i think they have older cars. Some running alright but i would avoid them. They do have some good prices on the newer cars though. Just dont rent from Petra. They have lousy cars and they rip their clients off. The charge their credit cards without consent and then refuse to help settle the issue.</RelCText>
		</RelComment>
	</Thread>
</OrgQuestion>

<OrgQuestion ORGQ_ID="Q201">
	<OrgQSubject>which mobile is best under 2000QR</OrgQSubject>
	<OrgQBody>i want to buy new mobile.... and i want to know which mobile is best is under 2000QR....</OrgQBody>

	<Thread THREAD_SEQUENCE="Q201_R23" SubtaskA_Skip_Because_Same_As_RelQuestion_ID="Q60_R26">
		<RelQuestion RELQ_ID="Q201_R23" RELQ_RANKING_ORDER="23" RELQ_CATEGORY="Qatar Living Lounge" RELQ_DATE="2009-08-02 11:44:14" RELQ_USERID="U181" RELQ_USERNAME="Gypsy" RELQ_RELEVANCE2ORGQ="Irrelevant">
			<RelQSubject>What happens if I break my lease in Doha?</RelQSubject>
			<RelQBody>My lease in my current place ends in December; but frankly I'm sick of paying for my overpriced rent while all around me prices are dropping. I wonder if everyone knows what the legal repercutions are of skipping out on my lease?</RelQBody>
		</RelQuestion>

		<RelComment RELC_ID="Q201_R23_C1" RELC_DATE="2009-08-02 11:45:38" RELC_USERID="U2" RELC_USERNAME="anonymous" RELC_RELEVANCE2ORGQ="Bad" RELC_RELEVANCE2RELQ="Good">
			<RelCText>...and you can be out without hassles. One year clause is not legal. Source: - A study Conducted by FriedUnicorn - Vol I (September;1999)</RelCText>
		</RelComment>

		<RelComment RELC_ID="Q201_R23_C2" RELC_DATE="2009-08-02 11:45:52" RELC_USERID="U268" RELC_USERNAME="britexpat" RELC_RELEVANCE2ORGQ="Bad" RELC_RELEVANCE2RELQ="Good">
			<RelCText>You'll definitely lose your deposit and will probably get chased for the remainder of the rent.. why not just stay put for another few months..</RelCText>
		</RelComment>

		<RelComment RELC_ID="Q201_R23_C3" RELC_DATE="2009-08-02 11:47:13" RELC_USERID="U181" RELC_USERNAME="Gypsy" RELC_RELEVANCE2ORGQ="Bad" RELC_RELEVANCE2RELQ="Bad">
			<RelCText>I know. But it's a pain to keep waiting. I'm going to loose my deposit anyway thanks to some painting my old roomate did...so that's not really a concern.</RelCText>
		</RelComment>

		<RelComment RELC_ID="Q201_R23_C4" RELC_DATE="2009-08-02 11:56:04" RELC_USERID="U2041" RELC_USERNAME="HASMUB" RELC_RELEVANCE2ORGQ="Bad" RELC_RELEVANCE2RELQ="Bad">
			<RelCText>You can negotiate with your landlord; i paid half month rent only for breaching the lease agreement; it is best rather than paying overpriced flat</RelCText>
		</RelComment>

		<RelComment RELC_ID="Q201_R23_C5" RELC_DATE="2009-08-02 11:57:30" RELC_USERID="U181" RELC_USERNAME="Gypsy" RELC_RELEVANCE2ORGQ="Bad" RELC_RELEVANCE2RELQ="Bad">
			<RelCText>Good suggestion Hasmub. It's really bothering me that I can get a VILLA for 2000 QR less (and closer to my work to) then my apartment.</RelCText>
		</RelComment>

		<RelComment RELC_ID="Q201_R23_C6" RELC_DATE="2009-08-02 12:00:17" RELC_USERID="U210" RELC_USERNAME="DaRuDe" RELC_RELEVANCE2ORGQ="Bad" RELC_RELEVANCE2RELQ="Bad">
			<RelCText>dont you have the contract ? havent you read it??</RelCText>
		</RelComment>

		<RelComment RELC_ID="Q201_R23_C7" RELC_DATE="2009-08-02 12:07:16" RELC_USERID="U181" RELC_USERNAME="Gypsy" RELC_RELEVANCE2ORGQ="Bad" RELC_RELEVANCE2RELQ="Bad">
			<RelCText>That would be the smart thing to do Da. :P</RelCText>
		</RelComment>

		<RelComment RELC_ID="Q201_R23_C8" RELC_DATE="2009-08-02 12:18:28" RELC_USERID="U2" RELC_USERNAME="anonymous" RELC_RELEVANCE2ORGQ="Bad" RELC_RELEVANCE2RELQ="Good">
			<RelCText>you can give him one month notification befor u leave; if it in your rental contract.</RelCText>
		</RelComment>

		<RelComment RELC_ID="Q201_R23_C9" RELC_DATE="2009-08-02 12:21:36" RELC_USERID="U181" RELC_USERNAME="Gypsy" RELC_RELEVANCE2ORGQ="Bad" RELC_RELEVANCE2RELQ="Bad">
			<RelCText>Ya I just spoke to him and he says I have to pay the remainder of the rent. :S That seems a bit steep.</RelCText>
		</RelComment>

		<RelComment RELC_ID="Q201_R23_C10" RELC_DATE="2009-08-02 12:39:32" RELC_USERID="U181" RELC_USERNAME="Gypsy" RELC_RELEVANCE2ORGQ="Bad" RELC_RELEVANCE2RELQ="Bad">
			<RelCText>I know. I'm going to try and go in on Friday. However I know the best way to get to him is through his secretary.</RelCText>
		</RelComment>
	</Thread>
</OrgQuestion>

<OrgQuestion ORGQ_ID="Q201">
	<OrgQSubject>which mobile is best under 2000QR</OrgQSubject>
	<OrgQBody>i want to buy new mobile.... and i want to know which mobile is best is under 2000QR....</OrgQBody>

	<Thread THREAD_SEQUENCE="Q201_R24" SubtaskA_Skip_Because_Same_As_RelQuestion_ID="Q129_R61">
		<RelQuestion RELQ_ID="Q201_R24" RELQ_RANKING_ORDER="24" RELQ_CATEGORY="Qatar Living Lounge" RELQ_DATE="2009-08-31 11:13:03" RELQ_USERID="U3449" RELQ_USERNAME="jane01" RELQ_RELEVANCE2ORGQ="Relevant">
			<RelQSubject>Get Qatar Living for FREE w/ Vodafone Mobile?</RelQSubject>
			<RelQBody>Vodafone Qatar have just announced they will be offering free mobile internet until the end of September. That means you'll be able to browse Qatar Living to your hearts content for free :-) See you online! Update : iPhone 3GS in Qatar too.</RelQBody>
		</RelQuestion>

		<RelComment RELC_ID="Q201_R24_C1" RELC_DATE="2009-08-31 11:43:17" RELC_USERID="U210" RELC_USERNAME="DaRuDe" RELC_RELEVANCE2ORGQ="Bad" RELC_RELEVANCE2RELQ="Good">
			<RelCText>thats great.</RelCText>
		</RelComment>

		<RelComment RELC_ID="Q201_R24_C2" RELC_DATE="2009-08-31 11:55:24" RELC_USERID="U3450" RELC_USERNAME="ka78" RELC_RELEVANCE2ORGQ="Bad" RELC_RELEVANCE2RELQ="Good">
			<RelCText>Thanks Vodafone..;)</RelCText>
		</RelComment>

		<RelComment RELC_ID="Q201_R24_C3" RELC_DATE="2009-08-31 12:02:15" RELC_USERID="U3451" RELC_USERNAME="lewis_hamilton" RELC_RELEVANCE2ORGQ="Bad" RELC_RELEVANCE2RELQ="Good">
			<RelCText>unfortunately they r temporary offers</RelCText>
		</RelComment>

		<RelComment RELC_ID="Q201_R24_C4" RELC_DATE="2009-08-31 12:04:53" RELC_USERID="U61" RELC_USERNAME="smoke" RELC_RELEVANCE2ORGQ="Bad" RELC_RELEVANCE2RELQ="PotentiallyUseful">
			<RelCText>Whats the big deal? I get free QL everyday from office for the last 2 years and 18 weeks. I dont need QL on the go; coz then i'd really go crazy :p None the less good move from Vadaphones Good Fortune always comes knocking at your door...when you are sh*tting in the toilet!! :) _[]~ SMoKE ~[]_  </RelCText>
		</RelComment>

		<RelComment RELC_ID="Q201_R24_C5" RELC_DATE="2009-08-31 12:09:00" RELC_USERID="U3451" RELC_USERNAME="lewis_hamilton" RELC_RELEVANCE2ORGQ="Bad" RELC_RELEVANCE2RELQ="PotentiallyUseful">
			<RelCText>smoke u dont have to use QL on the go news or email or results for watever sports u like</RelCText>
		</RelComment>

		<RelComment RELC_ID="Q201_R24_C6" RELC_DATE="2009-08-31 12:11:58" RELC_USERID="U61" RELC_USERNAME="smoke" RELC_RELEVANCE2ORGQ="Bad" RELC_RELEVANCE2RELQ="Bad">
			<RelCText>Thats true; i was just referring to the title of the thread dude :) Good Fortune always comes knocking at your door...when you are sh*tting in the toilet!! :) _[]~ SMoKE ~[]_  </RelCText>
		</RelComment>

		<RelComment RELC_ID="Q201_R24_C7" RELC_DATE="2009-08-31 12:15:37" RELC_USERID="U405" RELC_USERNAME="bleu" RELC_RELEVANCE2ORGQ="PotentiallyUseful" RELC_RELEVANCE2RELQ="Good">
			<RelCText>WOW!!! So vodafone is giving us FREE phones with FREE sim cards and FREE 3g gprs usage!!! GREAT!!!!!! Where can I get the stuff? What has this got to do with QL? I thought QL is FREE? I didn't pay to use QL.</RelCText>
		</RelComment>

		<RelComment RELC_ID="Q201_R24_C8" RELC_DATE="2009-08-31 12:15:40" RELC_USERID="U3451" RELC_USERNAME="lewis_hamilton" RELC_RELEVANCE2ORGQ="Bad" RELC_RELEVANCE2RELQ="PotentiallyUseful">
			<RelCText>from the nameof the thread i thought it was another competeion thingy for winning a free line as a publicity stunt</RelCText>
		</RelComment>

		<RelComment RELC_ID="Q201_R24_C9" RELC_DATE="2009-08-31 12:18:27" RELC_USERID="U287" RELC_USERNAME="Xray" RELC_RELEVANCE2ORGQ="Bad" RELC_RELEVANCE2RELQ="Bad">
			<RelCText>i haven't tried yet but somebody was telling me that internet speed is much better than Qtel...</RelCText>
		</RelComment>

		<RelComment RELC_ID="Q201_R24_C10" RELC_DATE="2009-08-31 12:18:37" RELC_USERID="U61" RELC_USERNAME="smoke" RELC_RELEVANCE2ORGQ="Bad" RELC_RELEVANCE2RELQ="PotentiallyUseful">
			<RelCText>hold on no one said anything about free phones? What phones are they giving? So basically Vodafone is Vodafree? Good Fortune always comes knocking at your door...when you are sh*tting in the toilet!! :) _[]~ SMoKE ~[]_  </RelCText>
		</RelComment>
	</Thread>
</OrgQuestion>

<OrgQuestion ORGQ_ID="Q201">
	<OrgQSubject>which mobile is best under 2000QR</OrgQSubject>
	<OrgQBody>i want to buy new mobile.... and i want to know which mobile is best is under 2000QR....</OrgQBody>

	<Thread THREAD_SEQUENCE="Q201_R26">
		<RelQuestion RELQ_ID="Q201_R26" RELQ_RANKING_ORDER="26" RELQ_CATEGORY="Working in Qatar" RELQ_DATE="2015-01-07 10:00:25" RELQ_USERID="U4433" RELQ_USERNAME="komail" RELQ_RELEVANCE2ORGQ="Irrelevant">
			<RelQSubject>Salary vs Cost of Living Doha</RelQSubject>
			<RelQBody>Family with 2 kids (9 &amp; 5 years old) - both school going Salary package of 20K (with no other benefit) Is it a good deal?</RelQBody>
		</RelQuestion>

		<RelComment RELC_ID="Q201_R26_C1" RELC_DATE="2015-01-07 10:31:45" RELC_USERID="U4434" RELC_USERNAME="aamirjaved" RELC_RELEVANCE2ORGQ="Bad" RELC_RELEVANCE2RELQ="Good">
			<RelCText>For family with 2 child; you ll probably need 2BR flat which will cost about 7000-8000 and for schooling you ll probably need 4000-5000. so it means these two will take major chunk of your salary. Further you can take 3000 monthly living expense and 2000 for conveyance. Additionally any medical requirements. Now its upto you to decide...</RelCText>
		</RelComment>

		<RelComment RELC_ID="Q201_R26_C2" RELC_DATE="2015-01-07 10:43:17" RELC_USERID="U640" RELC_USERNAME="acchabaccha" RELC_RELEVANCE2ORGQ="Bad" RELC_RELEVANCE2RELQ="Good">
			<RelCText>Aamirjaved's calculation is somewhat on the high side. I believe you should be able to get a 2BR within QR 5000 and also you can easily manage your monthly expenses within QR 2000. For the schooling; if you are an Asian; it is not that costly to my understanding. As such; my view is that if you are an Asian; grab the offer; but if you are a westerner; kick it.</RelCText>
		</RelComment>

		<RelComment RELC_ID="Q201_R26_C3" RELC_DATE="2015-01-07 10:44:34" RELC_USERID="U4435" RELC_USERNAME="arkb" RELC_RELEVANCE2ORGQ="Bad" RELC_RELEVANCE2RELQ="PotentiallyUseful">
			<RelCText>We can't say if it's a good deal - you don't include details of the role. Try to get schooling included in the package. Agree with aamirjaved. Depends on what standard of living you want. Depending on area; you may need 10k+ for a nice 2 bed.</RelCText>
		</RelComment>

		<RelComment RELC_ID="Q201_R26_C4" RELC_DATE="2015-01-07 10:49:36" RELC_USERID="U4436" RELC_USERNAME="Viswakumar" RELC_RELEVANCE2ORGQ="Bad" RELC_RELEVANCE2RELQ="Bad">
			<RelCText>Agree with aamirjaved.</RelCText>
		</RelComment>

		<RelComment RELC_ID="Q201_R26_C5" RELC_DATE="2015-01-07 11:19:50" RELC_USERID="U4437" RELC_USERNAME="BISHWANATH2014" RELC_RELEVANCE2ORGQ="Bad" RELC_RELEVANCE2RELQ="Good">
			<RelCText>EZDAN 2 bedroom Fully Furnished you get in QR 5500; School Asian with Transportation for 2 kids 750 x2 = 1500 and QR 3000 living expense and QR 1000 miscellaneous. So Net Savings QR 9000 as of my 10 years experience in Doha living with Family.</RelCText>
		</RelComment>

		<RelComment RELC_ID="Q201_R26_C6" RELC_DATE="2015-01-07 11:55:01" RELC_USERID="U4438" RELC_USERNAME="mido-doha" RELC_RELEVANCE2ORGQ="Bad" RELC_RELEVANCE2RELQ="PotentiallyUseful">
			<RelCText>no enough for the near future as Qatar is getting more expensive not yearly! you can feel it every 4-5 months.</RelCText>
		</RelComment>

		<RelComment RELC_ID="Q201_R26_C7" RELC_DATE="2015-01-07 11:58:07" RELC_USERID="U4439" RELC_USERNAME="krohit_in" RELC_RELEVANCE2ORGQ="Bad" RELC_RELEVANCE2RELQ="PotentiallyUseful">
			<RelCText>I will suggest to go for unfurnished property; it will cost you around QR 4000-4800 depends on locality; Asian school with transportation for two kids 1000 X2= QR 2000; QR 2000 for living expense and QR 500 for transport; Total cost of living would be QR 8500 - 9300; You can save QR +10500; But it totally depends on your living standard.</RelCText>
		</RelComment>

		<RelComment RELC_ID="Q201_R26_C8" RELC_DATE="2015-01-07 12:08:47" RELC_USERID="U4440" RELC_USERNAME="Hamidpipi1" RELC_RELEVANCE2ORGQ="Bad" RELC_RELEVANCE2RELQ="PotentiallyUseful">
			<RelCText>1.2BHK - QR 5000/PM 2.Furniture Allowance Incl All house hold items (For one time = QR 14000 - 16000) for two bed room flat. Schooling for tow kids incl transport (Asian) = QR 1800 3.Net + Phone = QR 600 4. House living Expenses = QR 2500 5. Miscellaneous = QR 1000 if you are from India then the cost of living should be like Allmost the same.....</RelCText>
		</RelComment>

		<RelComment RELC_ID="Q201_R26_C9" RELC_DATE="2015-01-07 12:43:13" RELC_USERID="U68" RELC_USERNAME="Mary-vani" RELC_RELEVANCE2ORGQ="Bad" RELC_RELEVANCE2RELQ="Bad">
			<RelCText>if you have decided to join this Qatar company; you mus to attested your educational certificate.For attestation &amp; translation purpose please contact to sheenservices wll.. website:http://sheenservices.com/contact-us.html-44366147/55974495</RelCText>
		</RelComment>

		<RelComment RELC_ID="Q201_R26_C10" RELC_DATE="2015-01-07 13:47:59" RELC_USERID="U4124" RELC_USERNAME="yacine.h" RELC_RELEVANCE2ORGQ="Bad" RELC_RELEVANCE2RELQ="PotentiallyUseful">
			<RelCText>If you are Asian you should be fine with it. If you are European you wouldn't be fine with it all as the schools and the rent fees will eat up much of it</RelCText>
		</RelComment>
	</Thread>
</OrgQuestion>

<OrgQuestion ORGQ_ID="Q201">
	<OrgQSubject>which mobile is best under 2000QR</OrgQSubject>
	<OrgQBody>i want to buy new mobile.... and i want to know which mobile is best is under 2000QR....</OrgQBody>

	<Thread THREAD_SEQUENCE="Q201_R27" SubtaskA_Skip_Because_Same_As_RelQuestion_ID="Q159_R6">
		<RelQuestion RELQ_ID="Q201_R27" RELQ_RANKING_ORDER="27" RELQ_CATEGORY="Welcome to Qatar" RELQ_DATE="2008-07-21 07:11:17" RELQ_USERID="U3871" RELQ_USERNAME="intrigue" RELQ_RELEVANCE2ORGQ="Irrelevant">
			<RelQSubject>How much should I expect to save in 20;000/- pm ?</RelQSubject>
			<RelQBody>Hi; How much should I expect to save in 20;000/- pm. I am married with no kids and considering a reasonable life style. This is an all in pay i.e I would have to take care of my housing also Also what is the cost of car rental / Loan in Qatar ?</RelQBody>
		</RelQuestion>

		<RelComment RELC_ID="Q201_R27_C1" RELC_DATE="2008-07-21 07:27:28" RELC_USERID="U2217" RELC_USERNAME="michoo123" RELC_RELEVANCE2ORGQ="Bad" RELC_RELEVANCE2RELQ="Good">
			<RelCText>QR 20;000 is good salary to live in qatar. As only u and wife u can get a small flat around QR 4;000 &amp; living expense depend upon ur life style vary from 1;500 - 4;000. Car rental is 2;000 avg for good saloon car &amp; loan if u going for small car; loan payment will be from 800 to 1500 depends upon number of years. so atleast a month u can safe upto 6 to 8 thousand.</RelCText>
		</RelComment>

		<RelComment RELC_ID="Q201_R27_C2" RELC_DATE="2008-07-21 07:27:50" RELC_USERID="U932" RELC_USERNAME="Geechee_bu" RELC_RELEVANCE2ORGQ="Bad" RELC_RELEVANCE2RELQ="Good">
			<RelCText>I am giving you the figures which may give you an idea about cost of living here. Hope this will help you to calculate your mothly savings and expected salary: Housing Rent is exorbitantly high in Qatar. If you want decent place to live then you have to be ready to spend around 7500 to 9500. QAR (Per Month) For 2 Persons 8;500 House Rent (Furnished) 1;800 Groceries+ Misc exps. 1;600 Car Hire / OR Loan installment + Petrol 33 Land Line Rent 50 Mobile Rent OR Prepaid Card 150 Water Charges 150 Electricity 200 Internet at home 75 Television Channel Connection 120 VOIP Call Card to call home country 200 Car Insurance (2500/12)if you own your car ____________ 12;878 Total One Time Exps. 1;000 Deposit for Water Connection 1;000 Deposit for Ele. Connection 7;500 House Rent Deposit 2;000 Driving Classes Fees (Appx.) 250 One Time Mobile activation Charges _____________________ 11;750 Total</RelCText>
		</RelComment>

		<RelComment RELC_ID="Q201_R27_C3" RELC_DATE="2008-07-21 08:09:41" RELC_USERID="U188" RELC_USERNAME="novita77" RELC_RELEVANCE2ORGQ="Bad" RELC_RELEVANCE2RELQ="Bad">
			<RelCText>to Michoo... do tell us where to get a flat for QR 4000</RelCText>
		</RelComment>

		<RelComment RELC_ID="Q201_R27_C4" RELC_DATE="2008-07-21 08:47:26" RELC_USERID="U2" RELC_USERNAME="anonymous" RELC_RELEVANCE2ORGQ="Bad" RELC_RELEVANCE2RELQ="Bad">
			<RelCText>wow...complete details from Geechee...u must put a consultancy firm.thanks</RelCText>
		</RelComment>

		<RelComment RELC_ID="Q201_R27_C5" RELC_DATE="2008-07-21 08:57:54" RELC_USERID="U3872" RELC_USERNAME="drmedo" RELC_RELEVANCE2ORGQ="Bad" RELC_RELEVANCE2RELQ="PotentiallyUseful">
			<RelCText>Room for 4;000 not Flat Small flat start at 6;000</RelCText>
		</RelComment>

		<RelComment RELC_ID="Q201_R27_C6" RELC_DATE="2008-07-21 10:32:18" RELC_USERID="U3864" RELC_USERNAME="Mercia" RELC_RELEVANCE2ORGQ="Bad" RELC_RELEVANCE2RELQ="Good">
			<RelCText>I think it will depend on what kind of lifestyle you want here; what nationality are you? If you are western I would say you wont save much out of 20k; you would want a decent apartment / villa; good social life; weekends away. If you are the sort of person who is just coming here to work work work; then you will be able to save more. It will be trial and error until you find the balance that suits you and the lifestyle you want to have.</RelCText>
		</RelComment>

		<RelComment RELC_ID="Q201_R27_C7" RELC_DATE="2008-07-21 12:11:35" RELC_USERID="U2217" RELC_USERNAME="michoo123" RELC_RELEVANCE2ORGQ="Bad" RELC_RELEVANCE2RELQ="PotentiallyUseful">
			<RelCText>Hi Notiva; U do get unfurnished one bedroom flat for QR 4;000 ideal for small family.</RelCText>
		</RelComment>

		<RelComment RELC_ID="Q201_R27_C8" RELC_DATE="2008-07-21 12:15:18" RELC_USERID="U2217" RELC_USERNAME="michoo123" RELC_RELEVANCE2ORGQ="Bad" RELC_RELEVANCE2RELQ="PotentiallyUseful">
			<RelCText>Hi Drmedo; Please check this we can get accomodation even less QR 4000</RelCText>
		</RelComment>

		<RelComment RELC_ID="Q201_R27_C9" RELC_DATE="2008-07-21 12:16:24" RELC_USERID="U2217" RELC_USERNAME="michoo123" RELC_RELEVANCE2ORGQ="Bad" RELC_RELEVANCE2RELQ="PotentiallyUseful">
			<RelCText>Price: 2 700QR Bedrooms: 1 Furniture: Semi-furnished Contact number: 5670013 Type: Villa (Compound) Type of listing: For Rent Description: FULL INDEPENDENT WITH SEPARATE ENTRANCE SEMI FURNISHED ONE BED ROOM + KITCHEN + BATHROOM + LARGE OPEN YARD IN DAFNA AREA OPPOSITE TO UNIVERSITY PETROL STATION AND JUST BEHIND OF WEST BAY HEALTH CENTR. MOTHLY RENT ENCLUDING E/W: 2700 Q. R. FOR CONTACT: 5670013</RelCText>
		</RelComment>

		<RelComment RELC_ID="Q201_R27_C10" RELC_DATE="2008-07-23 15:43:56" RELC_USERID="U3873" RELC_USERNAME="Doha Sun" RELC_RELEVANCE2ORGQ="Bad" RELC_RELEVANCE2RELQ="PotentiallyUseful">
			<RelCText>I see a lot of people have already written a reasonable answer; but keep in mind following: - about flat or car rental - depends who negotiates. If a European person or a westerner in general - forget it to find those rates. For them everything is double. - as many have mentioned - depends on lifestyle. For example one of the most difficult issues for women here - to find a normal hairdresser; beautician; etc. usually too expensive and very low quality / level of hygiene. If you go to a normal place - prices are ridiculous for what you get.</RelCText>
		</RelComment>
	</Thread>
</OrgQuestion>

<OrgQuestion ORGQ_ID="Q201">
	<OrgQSubject>which mobile is best under 2000QR</OrgQSubject>
	<OrgQBody>i want to buy new mobile.... and i want to know which mobile is best is under 2000QR....</OrgQBody>

	<Thread THREAD_SEQUENCE="Q201_R29">
		<RelQuestion RELQ_ID="Q201_R29" RELQ_RANKING_ORDER="29" RELQ_CATEGORY="Doha Shopping" RELQ_DATE="2011-01-24 22:32:54" RELQ_USERID="U4441" RELQ_USERNAME="sakib12345" RELQ_RELEVANCE2ORGQ="Irrelevant">
			<RelQSubject>Why to DSLR cams cost more in Qatar ?</RelQSubject>
			<RelQBody>i see that the prices are higher in Qatar on DSLR cams ? why is it? can any one suggest how i can by cheaper online. i dont have any experience buying things online. so i need advices :)</RelQBody>
		</RelQuestion>

		<RelComment RELC_ID="Q201_R29_C1" RELC_DATE="2011-01-24 22:39:19" RELC_USERID="U643" RELC_USERNAME="lamea" RELC_RELEVANCE2ORGQ="Bad" RELC_RELEVANCE2RELQ="PotentiallyUseful">
			<RelCText>every thing is expensive here.</RelCText>
		</RelComment>

		<RelComment RELC_ID="Q201_R29_C2" RELC_DATE="2011-01-24 22:39:44" RELC_USERID="U578" RELC_USERNAME="flexicode" RELC_RELEVANCE2ORGQ="Bad" RELC_RELEVANCE2RELQ="PotentiallyUseful">
			<RelCText>better stay away from online purchases; especially if you want it to be delivered on a qatar address; that too a digicam...DSLR prices are higher in qatar as compared to where?</RelCText>
		</RelComment>

		<RelComment RELC_ID="Q201_R29_C3" RELC_DATE="2011-01-24 22:45:42" RELC_USERID="U4441" RELC_USERNAME="sakib12345" RELC_RELEVANCE2ORGQ="Bad" RELC_RELEVANCE2RELQ="Good">
			<RelCText>on amazon.com it says Canon EOS Rebel T1i 15.1 MP CMOS Digital SLR Camera with 3-Inch LCD and EF-S 18-55mm f/3.5-5.6 IS Lens @ $589.99 :|</RelCText>
		</RelComment>

		<RelComment RELC_ID="Q201_R29_C4" RELC_DATE="2011-01-24 22:55:49" RELC_USERID="U4441" RELC_USERNAME="sakib12345" RELC_RELEVANCE2ORGQ="Bad" RELC_RELEVANCE2RELQ="PotentiallyUseful">
			<RelCText>Canon EOS Rebel T1i (canon 500D) in Qatar is Qr.2998 which is around $821............</RelCText>
		</RelComment>

		<RelComment RELC_ID="Q201_R29_C5" RELC_DATE="2011-01-24 22:55:57" RELC_USERID="U578" RELC_USERNAME="flexicode" RELC_RELEVANCE2ORGQ="Bad" RELC_RELEVANCE2RELQ="PotentiallyUseful">
			<RelCText>you can get this for about the same price (around 2000 QR) here as well but you need to check at 3 - 4 places for a comparison. there is an undefinable difference in prices even on major brands here in qatar...</RelCText>
		</RelComment>

		<RelComment RELC_ID="Q201_R29_C6" RELC_DATE="2011-01-24 22:59:34" RELC_USERID="U4441" RELC_USERNAME="sakib12345" RELC_RELEVANCE2ORGQ="Bad" RELC_RELEVANCE2RELQ="Bad">
			<RelCText>i checked lulu &amp; carrefour and the prices i found are Qr.2999 &amp; 2998......... where do i find it @ Qr.2000 here?</RelCText>
		</RelComment>

		<RelComment RELC_ID="Q201_R29_C7" RELC_DATE="2011-01-24 23:07:08" RELC_USERID="U4442" RELC_USERNAME="omar1733" RELC_RELEVANCE2ORGQ="Bad" RELC_RELEVANCE2RELQ="Good">
			<RelCText>Because there are not too much specialty stores that caters only professional cameras (DSLRs). Mostly camera stores can be found only in malls but they are not specialty stores. You know how mall owners jack-up prices of goods; especially if it comes or imported outside Doha. If you have friends in UAE; you can ask them to buy you one and just shipped it you. Or; there are some people selling DLSRs here in QL. You can search the classified ad here.</RelCText>
		</RelComment>

		<RelComment RELC_ID="Q201_R29_C8" RELC_DATE="2011-01-24 23:12:04" RELC_USERID="U4441" RELC_USERNAME="sakib12345" RELC_RELEVANCE2ORGQ="Bad" RELC_RELEVANCE2RELQ="Bad">
			<RelCText>omar1733 @ thanx mate...i'll check :)</RelCText>
		</RelComment>

		<RelComment RELC_ID="Q201_R29_C9" RELC_DATE="2011-01-24 23:13:17" RELC_USERID="U4442" RELC_USERNAME="omar1733" RELC_RELEVANCE2ORGQ="Bad" RELC_RELEVANCE2RELQ="Good">
			<RelCText>You can try Gulf Foto in Musheirib area.</RelCText>
		</RelComment>

		<RelComment RELC_ID="Q201_R29_C10" RELC_DATE="2011-01-25 00:52:27" RELC_USERID="U1304" RELC_USERNAME="cdpascual" RELC_RELEVANCE2ORGQ="Bad" RELC_RELEVANCE2RELQ="Good">
			<RelCText>you can try b&amp;h which is a trusted one; they can ship here.OR if you know somebody in US or travelling there you can ask them to buy it for you. that's what i did. my friend had ordered too from some sellers in ebay; mostly D90.</RelCText>
		</RelComment>
	</Thread>
</OrgQuestion>

<OrgQuestion ORGQ_ID="Q201">
	<OrgQSubject>which mobile is best under 2000QR</OrgQSubject>
	<OrgQBody>i want to buy new mobile.... and i want to know which mobile is best is under 2000QR....</OrgQBody>

	<Thread THREAD_SEQUENCE="Q201_R31" SubtaskA_Skip_Because_Same_As_RelQuestion_ID="Q42_R1">
		<RelQuestion RELQ_ID="Q201_R31" RELQ_RANKING_ORDER="31" RELQ_CATEGORY="Welcome to Qatar" RELQ_DATE="2010-05-29 15:04:41" RELQ_USERID="U1414" RELQ_USERNAME="dev.in.doha" RELQ_RELEVANCE2ORGQ="Irrelevant">
			<RelQSubject>How much traffic violation fine u have paid??</RelQSubject>